name: mr_meal
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  go_router: ^14.2.3
  sentry_flutter: ^8.7.0
  flutter_native_splash: ^2.4.1
  intl: ^0.19.0
  dio: ^5.6.0
  cached_network_image: ^3.4.1
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  shared_preferences: ^2.3.2
  device_preview: ^1.2.0
  flutter_layout_grid: ^2.0.7
  flutter_secure_storage: ^9.2.2
  rxdart: ^0.27.7
  shimmer: ^3.0.0
  carousel_slider: ^5.0.0
  path_provider: ^2.1.4
  sembast: ^3.7.3+2
  sembast_web: ^2.4.0+2
  google_maps_flutter: ^2.9.0
  location: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  analyzer: ^6.4.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
